### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by noeldum** [wb-08/PokerTableRecognize#3]
What version of Cython is required?

I first had issues with installing the requirements.txt. It came complaining about Cypthon.

```
pip3 install -r requirements.txt
Collecting eval7==0.1.9
  Downloading eval7-0.1.9.tar.gz (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.4/158.4 KB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8mamd9xs/eval7_d214e38fc83644ed964a27cb98b474fb/setup.py", line 3, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

```

So I installed Cyphon manually inside the venv. Fine here.

However now it comes with a different problem when installing the requirements.

```
pip3 install -r requirements.txt
Collecting eval7==0.1.9
  Using cached eval7-0.1.9.tar.gz (158 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [300 lines of output]
      /tmp/PokerVision/venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-4s7d2jzo/eval7_cd9fe2e2510e458cbed8e6e8ac213ccf/eval7/cards.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/PokerVision/venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-4s7d2jzo/eval7_cd9fe2e2510e458cbed8e6e8ac213ccf/eval7/equity.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      #
      # This software may be modified and distributed under the terms
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
     ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:7:0: 'xorshift_rand.pxd' not found

... plus some more
```

Would you be able to help?

I am on Ubuntu 22.04.4 LTS

**Comment by noeldum** [comment]
I am on Ubuntu 22.04.4 LTS

Can we run this without compiling with cython maybe?

**Comment by noeldum** [comment]
I started all from scratch again. This time installing cyphon and all other packages manually using pip3.
They all install ok except for eval7==0.1.9.

This is the full error message below.

```
pip3 install eval7==0.1.9
Collecting eval7==0.1.9
  Using cached eval7-0.1.9.tar.gz (158 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [300 lines of output]
      /home/nono/Documents/Poker/software/PokerVision/venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-chmxwx3f/eval7_656a06382621426ea14925376e5e6908/eval7/cards.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      /home/nono/Documents/Poker/software/PokerVision/venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-chmxwx3f/eval7_656a06382621426ea14925376e5e6908/eval7/equity.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      #
      # This software may be modified and distributed under the terms
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:7:0: 'xorshift_rand.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      #
      # This software may be modified and distributed under the terms
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:7:0: 'xorshift_rand/randint.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # This software may be modified and distributed under the terms
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      from evaluate cimport cy_evaluate
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:8:0: 'evaluate.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # This software may be modified and distributed under the terms
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      from evaluate cimport cy_evaluate
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:8:0: 'evaluate/cy_evaluate.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      from evaluate cimport cy_evaluate
      from cards cimport cards_to_mask
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:9:0: 'cards.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # of the MIT license.  See the LICENSE file for details.
      
      import cython
      from xorshift_rand cimport randint
      from evaluate cimport cy_evaluate
      from cards cimport cards_to_mask
      ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:9:0: 'cards/cards_to_mask.pxd' not found
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef unsigned long long deal_card(unsigned long long dead):
          cdef unsigned int cardex
          cdef unsigned long long card
          while True:
              cardex = randint(52)
                       ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:52:17: 'randint' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # deal the rest of the board
              dealt = hand | option
              board = start_board
              for j in range(5 - num_board):
                  board |= deal_card(board | dealt)
              hero = cy_evaluate(board | hand, 7)
                     ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:91:15: 'cy_evaluate' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              dealt = hand | option
              board = start_board
              for j in range(5 - num_board):
                  board |= deal_card(board | dealt)
              hero = cy_evaluate(board | hand, 7)
              villain = cy_evaluate(board | option, 7)
                        ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:92:18: 'cy_evaluate' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          return 0.5 * <double>count / <double>iterations
      
      
      def py_hand_vs_range_monte_carlo(py_hand, py_villain, py_board,
              py_iterations):
          cdef unsigned long long hand = cards_to_mask(py_hand)
                                         ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:102:35: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              py_iterations):
          cdef unsigned long long hand = cards_to_mask(py_hand)
          cdef int num_options = len(py_villain)
          cdef unsigned long long *options = <unsigned long long*>malloc(
                  sizeof(unsigned long long) * num_options)
          cdef unsigned long long start_board = cards_to_mask(py_board)
                                                ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:106:42: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef int num_board = len(py_board)
          cdef int iterations = py_iterations
          cdef float equity  # DuplicatedSignature
          cdef unsigned long long mask
          for index, option in enumerate(py_villain):
              options[index] = cards_to_mask(option[0])
                               ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:112:25: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          # because we know that every option is equally likely (unlike, for example,
          # range vs. range equity calculation).
          cdef unsigned int wins = 0
          cdef unsigned int ties = 0
          cdef unsigned long long option  # @DuplicatedSignature
          cdef unsigned int hero = cy_evaluate(complete_board | hand, 7)
                                   ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:134:29: 'cy_evaluate' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef unsigned int hero = cy_evaluate(complete_board | hand, 7)
          cdef unsigned int villain  # @DuplicatedSignature
          for i in range(num_options):
              # choose an option for opponent's hand
              option = options[i]
              villain = cy_evaluate(complete_board | option, 7)
                        ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:139:18: 'cy_evaluate' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  ties += 1
          return (wins + 0.5 * ties) / <double>num_options
      
      
      def py_hand_vs_range_exact(py_hand, py_villain, py_board):
          cdef unsigned long long hand = cards_to_mask(py_hand)  # @DuplicatedSignature
                                         ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:148:35: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      def py_hand_vs_range_exact(py_hand, py_villain, py_board):
          cdef unsigned long long hand = cards_to_mask(py_hand)  # @DuplicatedSignature
          cdef int num_options = len(py_villain)  # @DuplicatedSignature
          cdef unsigned long long *options = <unsigned long long*>malloc(
                  sizeof(unsigned long long) * num_options)  # @DuplicatedSignature
          cdef unsigned long long complete_board = cards_to_mask(py_board)
                                                   ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:152:45: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef unsigned long long complete_board = cards_to_mask(py_board)
          cdef float equity
          cdef unsigned long long mask  # @DuplicatedSignature
          cdef unsigned long long dead = complete_board | hand
          for index, option in enumerate(py_villain):
              options[index] = cards_to_mask(option[0])
                               ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:157:25: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef float *result = <float *>malloc(
                  sizeof(float) * len(py_hero))
      
          num_hands = 0
          for hand, weight in py_hero:
              hands[num_hands] = cards_to_mask(hand)
                                 ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:236:27: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              hands[num_hands] = cards_to_mask(hand)
              num_hands += 1
      
          num_options = 0
          for option, weight in py_villain:
              options[num_options] = cards_to_mask(option)
                                     ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:241:31: 'cards_to_mask' is not a constant, variable or function identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          num_options = 0
          for option, weight in py_villain:
              options[num_options] = cards_to_mask(option)
              num_options += 1
      
          board = cards_to_mask(py_board)
                  ^
      ------------------------------------------------------------
      
      eval7/equity.pyx:244:12: 'cards_to_mask' is not a constant, variable or function identifier
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-chmxwx3f/eval7_656a06382621426ea14925376e5e6908/setup.py", line 9, in <module>
          extensions = cythonize('eval7/*.pyx')
        File "/home/nono/Documents/Poker/software/PokerVision/venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/nono/Documents/Poker/software/PokerVision/venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: eval7/equity.pyx
      Compiling eval7/cards.pyx because it changed.
      Compiling eval7/equity.pyx because it changed.
      Compiling eval7/evaluate.pyx because it changed.
      Compiling eval7/xorshift_rand.pyx because it changed.
      [1/4] Cythonizing eval7/cards.pyx
      [2/4] Cythonizing eval7/equity.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Any ideas?

**Comment by noeldum** [comment]
Progressing. I have installed the latest eval7 instead and it works fine.
`pip3 install eval7==0.1.10`

Maybe the repo should be updated to install the latest eval7?

Now running into a different issue when trying to run it. I moved into the scripts directory as recommended then the launch fails giving this below.

```
python grab_table.py 
Traceback (most recent call last):
  File "/home/nono/Documents/Poker/software/PokerVision/scripts/grab_table.py", line 5, in <module>
    from pokerstars_recognition import PokerStarsTableRecognizer
  File "/home/nono/Documents/Poker/software/PokerVision/scripts/pokerstars_recognition.py", line 2, in <module>
    from scripts.table_recognition import PokerTableRecognizer
ModuleNotFoundError: No module named 'scripts'
```

Something is missing somewhere. Any help would be welcome.

**Comment by noeldum** [comment]
okay I had to manually edit these two files below
info_box.py
pokerstars_recognition.py

to remove the script.* to make it work.

Also I had to install wmctrl to get the program running. Maybe it should be mentioned in the readme too?

`sudo apt install wmctrl`

**Comment by wb-08** [comment]
> okay I had to manually edit these two files below info_box.py pokerstars_recognition.py
> 
> to remove the script.* to make it work.
> 
> Also I had to install wmctrl to get the program running. Maybe it should be mentioned in the readme too?
> 
> `sudo apt install wmctrl`

Better install all inside docker , if you have time, can you please wrap it up?
